### ISSUE TITLE
Enable OIDC based authentication to execute tf on cloud provider

### ISSUE THREAD

**Issue by stevengonsalvez** [dflook/terraform-github-actions#125]
>Example usage with azure. 

Environment variable of ARM_CLIENT_SECRET is used, which needs to be stored in secrets. Github OIDC has brought in federation with cloud providers enable cloud access tokens for authentication for the job duration - and removes the need for secret storage. 

More detail .:  https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure

The current session authentication with --federated-tokens is baked into azure/login action (which creates the session). But because the execution of tf is on another container - the session is not carried.

**Comment by dflook** [comment]
You'll need to provider whatever credentials you need to the container. GitHub makes this more awkward than it should be because it doesn't mount the job HOME dir into the container. 

Often you can use environment variables, which could be set explicitly for the terraform action or set by a previous step.
With AWS for example, the OIDC login action already sets the required environment variables so it just works.

I don't know Azure, so I don't know where you would find such credentials after using `azure/login`.

**Comment by stevengonsalvez** [comment]
Thanks, will probably dig a bit deep  feed into this issue.

**Comment by stevengonsalvez** [comment]
OIDC , seems to be supported now - although strangely not made its way to the main docs

https://github.com/hashicorp/terraform-provider-azurerm/pull/16555/files

**Comment by dflook** [comment]
Glad everything seems to be working. Closing as there doesn't seem to be any changes necessary to the actions.
