### ISSUE TITLE
Etags | terraform 1.0.8

### ISSUE THREAD

**Issue by Sunil-Jacob** [dflook/terraform-github-actions#168]
### Suggestion

Hi Daniel,

When running plan , etags keep trying to change and outputs the below plan

```
  ~ resource "google_project_iam_member" "token_creator_binding" ***
      ~ etag    = "BwXZJkbkR+M=" -> "BwXZYoNac4Q="
        id      = "***-321910/roles/iam.serviceAccountTokenCreator/serviceAccount:service-000012347349@gcp-sa-pubsub.iam.gserviceaccount.com"
        # (3 unchanged attributes hidden)
    ***
```

Upon checking it seems the recommended way to use as below in apply statement

`terraform apply -refresh-only`

Is it possible to add this?

**Comment by dflook** [comment]
Hi @Sunil-Jacob, where do you see this output?

Is it a change terraform has detected since the last apply (`Terraform detected the following changes made outside Terraform...`)? 
Or is it a change terraform is proposing to make (`Terraform will perform the following actions...`)?

Either way, a terraform apply will always refresh the state. There could be an action that just does a refresh, but I'm not sure I understand the use case.
