### ISSUE TITLE
OpenTofu support

### ISSUE THREAD

**Issue by kislerdm** [dflook/terraform-github-actions#297]
### Suggestion

@dflook Hey Daniel, would you be open to extending your great set of actions to support [OpenTofu](https://github.com/opentofu/opentofu)? It'd enable the community to try OpenTofu and help many engineers and organisations with migration. I'd be more than happy to contribute and help delivering required changes.

Thanks!

**Comment by dflook** [comment]
Hi @kislerdm, yes I think this will be an experimental option in the next release🙂

**Comment by kislerdm** [comment]
@dflook Great! Thank you for a prompt reply!

**Comment by Ant0wan** [comment]
Awesome, looking forward to use it !

**Comment by dflook** [comment]
This has been added in v1.37.0. New tofu actions have been added that are identical to the terraform actions, but use OpenTofu instead of Terraform for versions >= 1.6.0:

  - [dflook/tofu-version](tofu-version)
  - [dflook/tofu-remote-state](tofu-remote-state)
  - [dflook/tofu-output](tofu-output)
  - [dflook/tofu-validate](tofu-validate)
  - [dflook/tofu-fmt-check](tofu-fmt-check)
  - [dflook/tofu-fmt](tofu-fmt)
  - [dflook/tofu-check](tofu-check)
  - [dflook/tofu-plan](tofu-plan)
  - [dflook/tofu-apply](tofu-apply)
  - [dflook/tofu-destroy](tofu-destroy)
  - [dflook/tofu-new-workspace](tofu-new-workspace)
  - [dflook/tofu-destroy-workspace](tofu-destroy-workspace)
  - [dflook/tofu-unlock-state](tofu-unlock-state)

  As OpenTofu currently only has pre-release versions, OpenTofu will only be selected by using the exact version number.
  The easiest way to do this is by setting the `OPENTOFU_VERSION` environment variable, e.g in your workflow:

  ```yaml
    env:
        OPENTOFU_VERSION: 1.6.0-alpha3
  ```
  
  Setting `OPENTOFU_VERSION` with the `dflook/terraform-*` actions will cause it to behave as if it was the `dflook/tofu-*` action.

**Comment by kislerdm** [comment]
@dflook Hey Daniel! Thank you very much for your effort, much appreciated! 🚀

**Comment by kvendingoldo** [comment]
At this moment if you need to have a support of Terraform as well as OpenTofu (and Terragrunt :) ) in one tool you can use https://github.com/tofuutils/tenv which my team wrote some months ago. A lot of users switched to that tool to unify version management in the world of Terraform. 

You're welcome to open any issues or contribute to [tenv](https://github.com/tofuutils/tenv).
